1. 		i. Safety and Security
			ii. Clarity
			iii. Approachability
			iv. Developer Experience
       v. Intuiting Ownership with Resources
2.  The five pillars set the foundation for Cadence coding and the provide solid foundation to ensure the successful deployment of a code for a Smart Contract.  In building anything the foundation must be strong for the built structure to work as intended. Specifically:
			i. Safety and Security - ensure malicious attacks on the code are prevented for the users and developer
			ii. Clarity - simplicity of code for everyone to understand
			iii. Approachability - ease of use for all involved
       iv. Developer Experience - ease of problem solving to make the finish products better for everyone
